version: '3'

services:
  adoptapi:
    image: adoptapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - adopt-network
    depends_on:
      - "adoptmysql"

  adoptmysql:
    platform: linux/x86_64
    image: mysql
    command: [ '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adopt
      MYSQL_DATABASE: adopt
    ports:
      - "3307:3306"
    networks:
      - adopt-network

networks:
  adopt-network:
    driver: bridge